### ISSUE TITLE
Добавить в config/default.js атрибуты backendApiUrl и проброс его во вью с помощью конфига вебпака

### ISSUE THREAD

**Issue by justvitalius** [w3dip/statistics-ui#1]

**Comment by w3dip** [comment]
сделано, но в случае использования проксирования через nginx это получается не нужно, т.к. в противном случае идут кросс доменные запросы

**Comment by justvitalius** [comment]
По умолчанию вставим `/`.
Если придется разносить на разные сервера (один в РФ, другой в Германии), то этот конфиг очень придется кстати.
